### PR TITLE
feat(HEIC): Support HEIC in image magick.

### PR DESCRIPTION
**Pull request by bmcniel**
Adds libde265 and libheif to enable image magick to deal with HEIC
images.

https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

### CODE REVIEW

**Comment by MotoMcBoto** [comment]
This change is [Reviewable](https://reviewable.io/reviews/motorefi/heroku-buildpack-imagemagick7/5)

**Review by bmcniel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/motorefi/heroku-buildpack-imagemagick7/5)* status: 0 of 1 approvals obtained (waiting on @dave-motorefi, @ricardo-motorefi, and @SpainTrain)

___
*[bin/compile, line 74 at r1](https://reviewable.io/reviews/motorefi/heroku-buildpack-imagemagick7/5#-LuizIHv38rQwN95lsK4:-LuizIHw7YJCHfR-xp0a:b-hbncdn) ([raw file](https://github.com/motorefi/heroku-buildpack-imagemagick7/blob/2ff64fa6fa78f571eb9eb100715aa494ef17de35/bin/compile#L74)):*
> ```
> echo "-----> Updating environment variables"
> PROFILE_PATH="$BUILD_DIR/.profile.d/imagemagick.sh"
> ACTUAL_INSTALL_PATH="$HOME/vendor/imagemagick"
> ```

BTW, this unifies all the various builds into one prefix, ie vendor vs vendor/liba, vendor/libb breaking it apart like that makes configuring the linker a pain with more than one lib.

**Comment by dave-motorefi** [comment]
Do you think it's worth creating a separate buildback for this so it can be tested in demo separately from prod?

**Comment by bmcniel** [comment]
I see what you mean. I could just use my fork of the image magick build pack to test on demo.

**Review by dave-motorefi — COMMENTED** [review]
:+1: 

> *[Reviewable](https://reviewable.io/reviews/motorefi/heroku-buildpack-imagemagick7/5#-:-Lujl6NaEaRk0my6Clmn:b-8fx2u7)* status: 0 of 1 approvals obtained (waiting on @dave-motorefi, @ricardo-motorefi, and @SpainTrain)

**Review by ricardo-motorefi — COMMENTED** [review]
Go Apple! 👍🏼

**Review by ricardo-motorefi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/motorefi/heroku-buildpack-imagemagick7/5)* status: 0 of 1 approvals obtained (waiting on @SpainTrain)

**Pull request merged**
